name: Build Android APK

on:
  workflow_dispatch: # Allows you to trigger the build manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Make Gradle Executable
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK Asset
        uses: actions/upload-artifact@v4
        with:
          name: royal-pharmacy-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
          
